/**
 * Bundle the executables into the publishable plugin package.
 *
 * Each binary becomes one self-contained ESM file. That is not only for
 * convenience: ClawHub's secret-provider preset contract requires the resolver
 * to be a single plugin-root-relative script run by `${node}`, so it cannot
 * rely on a node_modules tree being present beside it.
 *
 * Usage: node --experimental-strip-types scripts/build-plugin-package.ts
 */
import { build } from "esbuild"
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const pkgRoot = join(root, "packages/openclaw-proton-pass")
const binDir = join(pkgRoot, "bin")

/** Entry points, mapped to the binary name each becomes. */
const ENTRIES = {
  "openclaw-protonpass-resolver": "apps/resolver/src/main.ts",
  "openclaw-pass-run": "apps/pass-run/src/main.ts",
  "openclaw-mcp-auth-proxy": "apps/mcp-auth-proxy/src/main.ts",
  "openclaw-proton-pass": "apps/cli/src/main.ts",
  index: "packages/openclaw-proton-pass/src/index.ts"
} as const

/** OpenClaw host APIs imported by the plugin entry must stay external. */
const PLUGIN_EXTERNALS = ["openclaw", "openclaw/*"] as const

rmSync(binDir, { recursive: true, force: true })
mkdirSync(binDir, { recursive: true })

for (const [name, entry] of Object.entries(ENTRIES)) {
  const isPluginEntry = name === "index"
  await build({
    entryPoints: [join(root, entry)],
    outfile: join(binDir, `${name}.mjs`),
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    minify: false,
    // Source maps are uploaded to PostHog during the release, so a stack trace
    // from a bundled file resolves back to the TypeScript that produced it.
    // Without them an error report points at a line in a 2 MB bundle.
    sourcemap: true,
    // Executables bundle every dependency. The plugin entry imports OpenClaw's
    // SDK from the host install, so those imports stay external.
    external: isPluginEntry ? [...PLUGIN_EXTERNALS] : [],
    banner: isPluginEntry
      ? {
          js: [
            "// @generated by scripts/build-plugin-package.ts - edit the sources, not this file."
          ].join("\n")
        }
      : {
          js: [
            "#!/usr/bin/env node",
            "// @generated by scripts/build-plugin-package.ts - edit the sources, not this file.",
            // Bundled ESM loses the CJS interop globals some dependencies probe for.
            "import { createRequire as __createRequire } from 'node:module'",
            "const require = __createRequire(import.meta.url)"
          ].join("\n")
        },
    define: {
      // Stamped in at build time so reports say which release they came from.
      "process.env.OPP_VERSION": JSON.stringify(
        JSON.parse(readFileSync(join(pkgRoot, "package.json"), "utf8")).version
      )
    },
    logLevel: "warning"
  })
  console.log(`bundled ${name}.mjs`)
}

// The published package carries its own copies so npm and ClawHub both show
// the documentation and licence alongside the code.
for (const file of ["README.md", "LICENSE", "TELEMETRY.md"]) {
  copyFileSync(join(root, file), join(pkgRoot, file))
}

// One version number governs the npm package, install metadata, and manifest; a
// mismatch between them is the kind of thing nobody notices until an install
// resolves to the wrong release.
const packagePath = join(pkgRoot, "package.json")
const pkg = JSON.parse(readFileSync(packagePath, "utf8")) as {
  name: string
  version: string
  openclaw?: {
    install?: Record<string, unknown>
  }
}
const version = pkg.version
const manifestPath = join(pkgRoot, "openclaw.plugin.json")
const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as Record<string, unknown>
manifest["version"] = version
writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`)

const openclaw = (pkg.openclaw ??= {})
const install = (openclaw.install ??= {})
install["npmSpec"] = `${pkg.name}@${version}`
writeFileSync(packagePath, `${JSON.stringify(pkg, null, 2)}\n`)

console.log(`package built at version ${version}`)
